#!/usr/bin/env bash

function install() {
    #git pull origin master;

    rsync -br --suffix="~" dotfiles/ $HOME/ \
        && echo "Dotfiles has been copied (backups created with \"~\" suffix)."

    dir=`pwd`
    tools=${pwd}/tools

    echo $PATH | grep $tools

    if [ $? != 0 ]; then
        sed -i s+__SET_PATH__+":${tools}"+ $HOME/.bashrc
    else
        sed -i s+__SET_PATH__++ $HOME/.bashrc
    fi

    if [ $? == 0 ]; then
        echo ${tools} has been added to $PATH
    else
        echo .bashrc file has not been added due to setting $PATH error
        if [ -f $HOME/.bashrc~ ]; then
            mv $HOME/.bashrc~ $HOME/.bashrc
            echo .bashrc has been restored from backup
        fi
    fi

    if [ ! -d $HOME/.vim ]; then
        mkdir $HOME/.vim
    fi

    rsync -br --exclude=".*" ${dir}/.vim/ $HOME/.vim/
    curl curl -fsL https://raw.github.com/junegunn/vim-plug/master/plug.vim > $HOME/.vim/autoload/plug.vim

}

read -p "Are you sure you want to install dotfiles? (this may overwrite your existing files)" yn

case $yn in
    [Yy]* ) install;;
    [Nn]* ) exit;;
    * ) echo "Please answer yes or no.";;
esac
