#!/usr/bin/env bash

function install() {
    #git pull origin master;

    rsync -br --suffix="~" dotfiles/ $HOME/ \
        && echo "Dotfiles has been copied (backups created with \"~\" suffix)."

    dir=`pwd`
    tools=${dir}/tools

    sed -i s+__SET_PATH__+":${tools}"+ $HOME/.bashrc

    if [ $? == 0 ]; then
        echo ${tools} has been added to \$PATH
    else
        echo .bashrc file has not been added due to setting \$PATH error
        if [ -f $HOME/.bashrc~ ]; then
            mv $HOME/.bashrc~ $HOME/.bashrc
            echo .bashrc has been restored from backup
        fi
    fi

    if [ ! -d $HOME/.vim ]; then
        mkdir $HOME/.vim
    fi

    rsync -br --exclude=".*" ${dir}/.vim/ $HOME/.vim/
    curl -fsL https://raw.github.com/junegunn/vim-plug/master/plug.vim > $HOME/.vim/autoload/plug.vim
    curl -fsL http://www.vim.org/scripts/download_script.php?src_id=5991 > $HOME/.vim/syntax/swig.vim
    echo run :PlugInstall in vim to install plugins
}

read -p "Are you sure you want to install dotfiles? (this may overwrite your existing files)" yn

case $yn in
    [Yy]* ) install;;
    [Nn]* ) exit;;
    * ) echo "Please answer yes or no.";;
esac
